### ISSUE TITLE
"dig" problem since last update

### ISSUE THREAD

**Issue by josmellop** [visibilityspots/dockerfile-cloudflared#30]
I'm getting this error since last update:

`time.c:118: Operation not permitted timer.c:634: fatal error: RUNTIME_CHECK(isc_time_now((&now)) == 0) failed Aborted `

I don't know what's happening, but I found in google that maybe there is a problem with "dig"

**Comment by git-clone** [comment]
I have the same problem, happy to test anything if needed, looks like the date isn't being set/updated properly?? still just starting out with docker though so not sure if this is symptom or cause.

same error message showing in portainer:

> time.c:118: Operation not permitted timer.c:634: fatal error: RUNTIME_CHECK(isc_time_now((&now)) == 0) failed Aborted 

console into container and 'date' returns the incorrect date and 'dig' fails with error below

> 
> / $ date
> Sun Jan  0 00:100:4174038  1900
> / $ dig
> time.c:118: Operation not permitted
> timer.c:634: fatal error: RUNTIME_CHECK(isc_time_now((&now)) == 0) failed
> Aborted
> / $ 

I build from a docker compose file. (v2) I have built with and without specifying the time zone. Same problem both times.

>   blue-cloudflared:
>     container_name: blue-cloudflared
>     image: visibilityspots/cloudflared
>     hostname: blue-cloudflared
>     networks:
>       VLAN3_network:
>         ipv4_address: 192.168.3.251
>     ports:
>       - "53:53/tcp"
>       - "53:53/udp"
>     environment:
>       TZ: GB
>       DNS1: 9.9.9.9
>       UPSTREAM1: "https://9.9.9.9/dns-query"
>       DNS2: 149.112.112.112
>       UPSTREAM2: "https://149.112.112.112/dns-query"
>       PORT: 53
>     restart: always

I have also tried deleting the image and container and pulling it down again. same issue.

**Comment by visibilityspots** [comment]
@git-clone @josmellop could you specify on which underlying architecture you are running the container upon? I just tested it on some platforms (amd64 & arm-v7) and the dig command works fine on them.

```
# docker image inspect visibilityspots/cloudflared:latest | grep Arch 
        "Architecture": "arm",
# docker image inspect visibilityspots/cloudflared:latest | grep Variant
        "Variant": "v7",
```

**Comment by josmellop** [comment]
Mine is in Raspberry Pi 4 (4GB RAM), so it's ARM. 
Previously to this last update, everything was working fine, but now this is what happens :(

**Comment by visibilityspots** [comment]
the only difference between the updates is an updated alpine container.. Could you try to build the docker image manually on the pi with the Dockerfile adjustment of 

```
...
FROM alpine
...
```

```
...
FROM alpine:3.12.3
...
```

```
docker build -t cloudflared-alpine:edge .
```

and then run that image on the pi

```
docker run --name cloudflared --rm --net host cloudflared-alpine:edge
```

**Comment by josmellop** [comment]
It's the first image I build in my Raspberry, so maybe I am doing something wrong, but I can't finish the build because of:

```
Status: Downloaded newer image for golang:alpine
 ---> 6eb1533cb254
Step 2/19 : RUN apk add --no-cache git gcc build-base;     go get -v github.com/cloudflare/cloudflared/cmd/cloudflared
 ---> Running in c39bdf78e01b
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/armv7/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/armv7/APKINDEX.tar.gz
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: temporary error (try again later)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/community: temporary error (try again later)
ERROR: unable to select packages:
  build-base (no such package):
    required by: world[build-base]
  gcc (no such package):
    required by: world[gcc]
  git (no such package):
    required by: world[git]
```

Maybe the alpine repository is unstable right now?
Sorry but I tryed several time but I'm unable to get the "apk add git..." command to work.

**Comment by josmellop** [comment]
Well, this is getting complicated, this is a problem with Raspberry Buster (Raspbian)
https://github.com/alpinelinux/docker-alpine/issues/110

Other dockers had the same problem, so maybe I can't build the image from my raspberry :(

**Comment by git-clone** [comment]
Apologies for the late reply, I am running this on a Pi4 too, I also use that linuxserver plex container mentioned above. If I had a memory I would have recalled I had seen that error already and may have put two and two together...

**Comment by visibilityspots** [comment]
hi

in the meanwhile I crafted a docker image based on alpine 3.12.3 which is available as [visibilityspots/cloudflared:edge](https://hub.docker.com/layers/134133712/visibilityspots/cloudflared/edge/images/sha256-113fb81aab8cbf308aa93341ba9b9f7f852a61ecd0baf9494881daedfb60aa19?context=explore) could one of you try out this image?

which OS are you running on the pi4? Since I do use a pi4 myself running arch linux arm underneath where I don't see that timing issue popping up..

**Comment by josmellop** [comment]
Like it was expected, with that version of alpine, it's working fine now. 0 problems
I'm running "Raspbian GNU/Linux 10 (buster)". I can't recall the problem with other container (like linuxserver/plex), but it is related with raspbian 32bits, and an outdated version of "libseccomp2" 
https://github.com/linuxserver/docker-plex/issues/247#issuecomment-733675170
Maybe here is another problem, but probably is also related to that.

What arch linux are you using?

**Comment by visibilityspots** [comment]
I configured https://archlinuxarm.org/platforms/armv8/broadcom/raspberry-pi-4 on my pi nodes in my [nomad](http://nomadproject.io) cluster. 

Great to hear it's working, too bad it's broken in the newer alpine version which I do not have control over :( . In the meanwhile I pushed some changes in the automation flow so there will be automated images available for the previous version of alpine too. 

As soon as this build is finished I will come back with the new image tag and once you confirmed that one is working I'll close this ticket if that's alright for you?

**Comment by josmellop** [comment]
Yes, it's working fine now. If you keep both images up-to-date I would really appreciate it, since the problem is with Raspbian, and until I change the linux distribution, this issue won't dissapear.

Thank you very much!

**Comment by visibilityspots** [comment]
alright, I've added the tags alpine3.13 and [alpine3.12](https://hub.docker.com/layers/visibilityspots/cloudflared/alpine-3.12/images/sha256-90e903add6cc311031cfc1899f8b12090c075482b55b6f26ebf576056ff936fc?context=explore).

Those will be maintained both through the pipeline. I'll close this issue. If you encounter issues let me know :)

**Comment by chrisbsmith** [comment]
Resurfacing this issue because I'm getting an unhealthy docker container for the latest `latest` and `alpine-3.13` tags.

I'm running on a RPi3.

```

# docker image inspect visibilityspots/cloudflared:latest | grep Variant
#
# docker image inspect visibilityspots/cloudflared:latest | grep Arch
        "Architecture": "arm",
#
# docker image inspect visibilityspots/cloudflared:alpine-3.13 | grep Arch
        "Architecture": "arm",
#
# docker image inspect visibilityspots/cloudflared:alpine-3.13 | grep Variant

#
```

When manually running the health check on the docker container, I get the following

```
# docker exec -it cloudflared sh
/ $ nslookup -po=5054 cloudflare.com 127.0.0.1
time.c:126: Operation not permitted
timer.c:617: fatal error: RUNTIME_CHECK(isc_time_now((&now)) == 0) failed
Aborted
/ $
```

The container seems to be working because I get expected results when running a [browser check ](https://www.cloudflare.com/ssl/encrypted-sni/)

**Comment by m1009d** [comment]
Hi guys, the same problem here on my raspberry pi 4 (latests updates, Debian Buster 32bit). Maybe just to explain the problem little bit more : **this is a known issue in Debian Buster 32bit when using Alpine 3.13+ version**: [https://docs.linuxserver.io/faq#my-host-is-incompatible-with-images-based-on-ubuntu-focal]

```sh
pi@raspberrypi:~/pihole $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian

pi@raspberrypi:~/pihole $ uname -a
Linux raspberrypi 5.10.63-v7l+ #1496 SMP Wed Dec 1 15:58:56 GMT 2021 armv7l GNU/Linux
```

### Steps to reproduce:

- run the `cloudflared` container as follows:
 
```sh
docker run -d \
    --name cloudflared \
    --rm \
    -e DNS1="1.1.1.1" \
    -e DNS2="1.0.0.1" \
    --restart=unless-stopped \
    --net host \
    visibilityspots/cloudflared
```

### docker container state is `unhealthy`
```
pi@raspberrypi:~/pihole $ docker ps
CONTAINER ID   IMAGE                         COMMAND                  CREATED          STATUS                      PORTS     NAMES
3b219bd1f4fc   visibilityspots/cloudflared   "/bin/sh -c '/usr/lo…"   13 minutes ago   Up 13 minutes (unhealthy)             cloudflared

# date is incorrectly set in the docker container which causes healthcheck to fail
pi@raspberrypi:~/pihole $ docker exec -it cloudflared /bin/sh

/ $ date
Wed Jul  1 01:33:04 UTC 2071        <<< This is wrong :)

/ $ nslookup 1.1.1.1
time.c:126: Operation not permitted
timer.c:617: fatal error: RUNTIME_CHECK(isc_time_now((&now)) == 0) failed
Aborted
/ $
```

### Solution: Add **`alpine-3.12`** tag and you are good to go

```sh
docker run -d \
    --name cloudflared \
    --rm \
    -e DNS1="1.1.1.1" \
    -e DNS2="1.0.0.1" \
    --restart=unless-stopped \
    --net host \
    visibilityspots/cloudflared:alpine-3.12
```

```sh
pi@raspberrypi:~/pihole $ docker ps
CONTAINER ID   IMAGE                                     COMMAND                  CREATED          STATUS                    PORTS     NAMES
659560d22f93   visibilityspots/cloudflared:alpine-3.12   "/bin/sh -c '/usr/lo…"   14 seconds ago   Up 13 seconds (healthy)             cloudflared

pi@raspberrypi:~/pihole $ docker exec -it cloudflared /bin/sh
/ $ date
Sun Dec 12 12:40:44 UTC 2021

/ $ nslookup 1.1.1.1
1.1.1.1.in-addr.arpa    name = one.one.one.one.

Authoritative answers can be found from:

/ $
```

#### NOTE: it doesn't work with `alpine-3.13` tag:

```sh
pi@raspberrypi:~/pihole $ docker ps
CONTAINER ID   IMAGE                                     COMMAND                  CREATED          STATUS                      PORTS     NAMES
12fbee6d086b   visibilityspots/cloudflared:alpine-3.13   "/bin/sh -c '/usr/lo…"   18 seconds ago   Up 16 seconds (unhealthy)             cloudflared

pi@raspberrypi:~/pihole $ docker exec -it cloudflared /bin/sh
/ $ date
Sun Jan  0 00:100:4174038  1900
/ $
```

**Comment by ericonr** [comment]
This was posted on #musl IRC but I don't see our comments posted here.

This is likely an issue caused by old seccomp filters in Docker that return EPERM for unknown syscalls, which confuses musl's time64 implementation (it checks for ENOSYS, which is what the kernel returns for unknown syscalls). It has been fixed on more recent docker releases.
